const COUNTRIES = [
  { name: "Argentina", flag: "🇦🇷", code: "ar" },
  { name: "Bolivia", flag: "🇧🇴", code: "bo" },
  { name: "Chile", flag: "🇨🇱", code: "cl" },
  { name: "Colombia", flag: "🇨🇴", code: "co" },
  { name: "Costa Rica", flag: "🇨🇷", code: "cr" },
  { name: "Cuba", flag: "🇨🇺", code: "cu" },
  { name: "Ecuador", flag: "🇪🇨", code: "ec" },
  { name: "El Salvador", flag: "🇸🇻", code: "sv" },
  { name: "Guatemala", flag: "🇬🇹", code: "gt" },
  { name: "Honduras", flag: "🇭🇳", code: "hn" },
  { name: "México", flag: "🇲🇽", code: "mx" },
  { name: "Nicaragua", flag: "🇳🇮", code: "ni" },
  { name: "Panamá", flag: "🇵🇦", code: "pa" },
  { name: "Paraguay", flag: "🇵🇾", code: "py" },
  { name: "Perú", flag: "🇵🇪", code: "pe" },
  { name: "Puerto Rico", flag: "🇵🇷", code: "pr" },
  { name: "República Dominicana", flag: "🇩🇴", code: "do" },
  { name: "Uruguay", flag: "🇺🇾", code: "uy" },
  { name: "Venezuela", flag: "🇻🇪", code: "ve" },
  { name: "España", flag: "🇪🇸", code: "es" }
];
